version: 0.0
os: linux
files:
  - source: /
    destination: /usr/cddemo
    overwrite: true
permissions:
  - object: /usr/cddemo/codedeploy
    pattern: "*.sh"
    owner: root
    group: root
    mode: 755
    type:
      - file
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 180
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 180
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 180